name: MineQuest-Citizens
main: net.teamio.minequest.citizens.MQAddonCitizens
version: ${build.number}

author: Xu_R

description: Adds Citizens2 support for MineQuest
website: www.theminequest.com

load: POSTWORLD
softdepend: [Spout,Citizens,MineQuest]

commands:
  mqnpc:
    description: View MineQuest Citizens NPC commands.
  contacts:
    description: Show all active contacts giving you quests.

permissions:
  minequest.command.mqnpc.*:
    description: Allows use of NPC management commands for MineQuest.
    default: op
    children:
      minequest.command.mqnpc.toggle: true
      minequest.command.mqnpc.check: true
      minequest.command.mqnpc.help: true
  minequest.command.mqnpc.toggle:
    description: Allows toggling the use of NPCs and giving quests.
    default: op
  minequest.command.mqnpc.check:
    description: Allows checking to see if NPCs are giving quests.
    default: op
  minequest.command.mqnpc.help:
    description: See the help menu.
    default: op
  minequest.command.contacts:
    description: Show all active contacts giving you quests.
    default: true
    children:
      minequest.command.contacts.help: true
  minequest.command.contacts.help:
    description: Show all active contacts giving you quests.
    default: true